include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    curly_braces_in_flow_control_structures: false
    use_key_in_widget_constructors: false
    avoid_dynamic_calls: false
